from src.core.validators.flight_validator import FlightValidator
from src.core.validators.passenger_validator import PassengerValidator
from src.core.validators.document_validator import DocumentValidator