from src.entities.airplane import Airplane
from src.entities.base_entity import BaseEntity
from src.entities.boarding_pass import BoardingPass
from src.entities.booking import Booking
from src.entities.document import Document
from src.entities.flight import Flight
from src.entities.passenger import Passenger
from src.entities.route import Route
from src.entities.ticket import Ticket
