name: Backend Pipeline - Airline Management System

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Check imports (isort)
      run: isort --check-only .

    - name: Check format (black)
      run: black --check .

    - name: Testing (pytest)
      env:
          PYTHONPATH: .
          TESTING: "True"
          DB_HOST: localhost
          DB_USER: root
          DB_TEST_PASS: test_password
          DB_TEST_NAME: airline_test
          DB_TEST_PORT: "3308"
      run: pytest -v